---
title: "downloading_data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{downloading_data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ChicagoHA)
```

View data topics
```{r}
topics <- cha_topics()
topics
```

Search by subcategory
```{r}
subcategories <- cha_topic_subcategories()
subcategories
```

```{r}
cha_topics("access-to-care")
```

View the populations, time periods, and geographies available for a topic
```{r}
coverage <- cha_coverage("POP")
coverage
```

Download the data for a topic within a population at a time period and a geographic scale
```{r}
data <- cha_data("POP", "H", "2014-2018", "zip")
```

Search geographic layers
```{r}
layers <- cha_layers()
layers
```

Download the geographic layer as an `sf` object
```{r}
cha_layer("neighborhood")
```

Search geographic points
```{r}
point_layers <- cha_point_layers()
point_layers
```

Download the point layer as an `sf` object

```{r}
point_layer <- cha_point_layer("67f58fa0-0dfa-4ee9-8600-c1ab4a093dc6")
```